language: python

python:
  - "3.5"
  - "3.6"

env:
  - REDIS_VERSION=2.10.6
  - REDIS_VERSION=3.2.1

# command to install dependencies
install:
  - pip install redis==$REDIS_VERSION
  - python setup.py install

# Setting up Databases and Services
services:
  - redis-server

# command to run tests
script: pytest