language: python

python:
  - "3.5"
  - "3.6"

env:
  - REDIS_VERSION=2.10.6
  - REDIS_VERSION=3.2.1

# command to install dependencies
install:
  - pip install redis==$REDIS_VERSION

# command to run tests
script: pytest